apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: db-deployment
    app: voting-app
  name: db-deployment
  namespace: vote
spec:
  replicas: 1
  selector: 
    matchLabels:
      name: postgres-pod
      app: voting-app
  template:
    metadata:
      labels:
        name: postgres-pod
        app: voting-app
      name: postgres-pod
    spec:
      containers:
      - name: postgres
        image: postgres:9.4
        env:
          - name: POSTGRES_HOST_AUTH_METHOD
            value: trust
        volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: db-data
      volumes:
        - name: db-data
          emptyDir: {}



