apiVersion: v1
kind: Service
metadata:
  labels:
    name: db
    app: voting-app
  name: db
  namespace: vote
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    name: postgres-pod
    app: voting-app

