apiVersion: v1
kind: Service
metadata:
  labels:
    name: redis
    app: voting-app
  name: redis
  namespace: vote
spec:
  type:  ClusterIP
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    name: redis-pod
    app: voting-app
