apiVersion: v1
kind: Service
metadata:
  labels:
    name: result-service
    app: voting-app
  name: result-service
  namespace: vote
spec:
  type: NodePort
  ports:
    - port: 5001
      targetPort: 80
      nodePort: 31001
  selector:
    name: result-pod
    app: voting-app

    