apiVersion: v1
kind: Service
metadata:
   labels:
    name: vote-service
    app: voting-app
   name: vote-service
   namespace: vote
spec:
   type: NodePort
   ports:
    - port: 5000
      targetPort: 80
      nodePort: 31000
   selector:
    name: vote-pod
    app: voting-app
