apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: worker
    app: voting-app
  name: worker
  namespace: vote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        name: worker-pod
        app: voting-app
      name:  worker-pod
    spec:
      containers:
      - name: worker
        image: kodekloud/examplevotingapp_worker